<?php

namespace ContainerYEOobBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9_OqcihService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9.Oqcih' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9.Oqcih'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepo' => ['privates', 'App\\Service\\ArticleService', 'getArticleServiceService', true],
            'categoryRepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'articleRepo' => 'App\\Service\\ArticleService',
            'categoryRepo' => 'App\\Repository\\CategoryRepository',
        ]);
    }
}
