<?php

namespace Container1tgjibx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CommentService' shared autowired service.
     *
     * @return \App\Service\CommentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CommentService.php';

        return $container->privates['App\\Service\\CommentService'] = new \App\Service\CommentService(($container->privates['App\\Repository\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['debug.serializer'] ?? $container->load('getDebug_SerializerService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['security.helper'] ?? $container->getSecurity_HelperService()));
    }
}
