<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1tgjibx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1tgjibx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1tgjibx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1tgjibx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1tgjibx\App_KernelDevDebugContainer([
    'container.build_hash' => '1tgjibx',
    'container.build_id' => '23cddb38',
    'container.build_time' => 1661021573,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1tgjibx');
